"""Ejercicios de pruebas de escritorio, realizar la prueba de escritorio correspondiente para los siguientes programas en Python: 

A) Determinar el valor de x, y, z en el print de la linea 4

1. x = True 
2. x = False 
3. y = False 
3. z = x and y
4. print(x,y,z) 
false

B) Determinar el mensaje mostrado por consola de las instrucciones print 

1. var1 = 22 
2. var2 = 33 
3. var3 = 44
4. if (var3 < var2):
5.	    var2 = var3 + var1
6. 	    var1 = var2
7.	    print("variable 1: ", var2, "variable 2: ", var2, "variable 3: ", var2)
7. else: 
    8. 	print("var2", "var1", "var3")
    var2, var1, var3

C) Determinar el valor de verdad de variable_boleana en las lineas 3 y 4. Determinar el resultado de las instrucciones print.

1. variable_booleana = True 
2. variable_booleana = False 
3. variable_booleana = variable_booleana and variable_booleana
4. variable_booleana = not(variable_booleana)
5. var_bool1 = True 
6. var_bool2 = False 
7. if (var_bool1 == True or var_bool2 == True)
8.	print(variable_booleana, "var_bool1", True)
9. print((var_bool1 or var_bool2) and (var_bool1 or var_bool2))
true, var_bool1, true
true"""
