"""La sucesión de Fibonacci es una sucesión de números enteros donde cada término se obtiene como suma de los dos anteriores, siendo los dos primeros 0 y 1.
Por lo tanto, Fib=0, 1, 1, 2, 3, 5, 8, 13, 21.... Realizar un programa que lea N e
imprima los N primeros términos de esta sucesión, como así también la suma de
los mismos."""
N = int(input("Ingrese un número entero positivo N: "))
if N <= 0:
    print("Entrada inválida. Por favor, ingrese un número entero positivo.")